config/routes.rb
Rails.application.routes.draw do
  get 'desafios/index'
  get 'home/index'
  resources :users
  get    'login'   => 'sessions#new'
  get    'home'    =>  'home#index'
  get    'desafios'    =>  'desafios#index'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  root 'sessions#new'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :name, presence: true, length: {maximum: 50} 
    validates :username, presence: true, length: {maximum: 50}, uniqueness: {case_sensitive: false}
    validates :password, presence: true, length: {minimum: 6}
    VALID_EMAIL_FORMAT=/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
    validates :email, presence: true, length: {maximum: 260}, format: { with: VALID_EMAIL_FORMAT}, uniqueness: {case_sensitive: false}
    before_save {self.email = email.downcase}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    include SessionsHelper
    def authorize
        unless logged_in?
          redirect_to root_url
        end
     end
    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
          redirect_to users_path
      end
    end
end

app/controllers/desafios_controller.rb
class DesafiosController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
before_action :block_access, except: [:destroy]
  def create
    @user = User.find_by(username: params[:session][:username])
                if @user && @user.authenticate(params[:session][:password])
                          sign_in(@user)
                          redirect_to current_user
                else
                          render action: :new
                end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
            @user = User.new
  end

  def create
            @user = User.new(user_params)
            if @user.save
                        redirect_to @user, notice: "Usuário foi criado com sucesso!"
                        sign_in(@user)
            else
            render action: :new
            end
  end
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path
    else
      render action: :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  before_action :authorize, except: [:new, :create]
  private
  def user_params
            params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/desafios_helper.rb
module DesafiosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def sign_in(user)
        session[:user_id] = user.id
    end
    def current_user
        if session[:user_id]
            @current_user ||= User.find_by(id: session[:user_id])
        end
    end
    def block_access
                if current_user.present?
                           redirect_to users_path
                end
    end
    def logged_in?
        !current_user.nil?
    end
    def sign_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/desafios/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="styles.css">
    <link href="https://fonts.googleapis.com/css?family=Bahiana|Barrio" rel="stylesheet">
</head>
<body>
    <h1>O <span id="header">Quiz</span> Aleatório</h1>
    <div class="quiz-container">
        <div id="quiz"></div>
    </div>
    <div id="progress-wrap">
        <div id="progress-bar"></div>
    </div>
    <button id="previous">Questão anterior</button>
    <button id="next">Próxima questão</button>
    <button onclick="moBt()" id="submit">Enviar</button>
    <button id="btnvid">Recompensa</button>
    <div id="results"></div>
    <div id="video"></div>
    <%= javascript_pack_tag 'main', 'data-turbolinks-track': 'reload' %>
</body>
</html>

app/views/home/index.html.erb
<head>
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700&display=swap" rel="stylesheet"/>

</head>
<body>
  <main>
    <div class="container">
      <%= image_tag("logoamar.png", width: 200) %>
      <span class="texto1"> Bem-Vindo ao<span>
      <span class="texto2"> Desafio Amar Educação</span>
      <span class="texto3">A ideia é bem simples, primeiro você se cadastra ou<span class="texto3"> loga no sistema,</span> e depois você terá que fazer uma série de desafios. <span class="texto3" >À medida que você completá-los você vai ganhando prêmios.</span><span class="texto3"> Agora vá se divertir.</span></span>
    </div>
  </main>
</body>

app/views/layouts/_header.html.erb
<head>
<%= javascript_pack_tag 'theme', 'data-turbolinks-track': 'reload' %>
</head>
<header>
    <% if logged_in? %>
    <nav class="navbar">
        <ul class="navbar-nav">
            <li class="logo">
              <a href="../home" class="nav-link">
                  <span class="link-text logo-text">Amar Educação</span>
                  <%= image_tag("logoamar.png", width: 80) %>
                  <i class="fas fa-chevron-right fa-angle-double-right fa-w-14 fa-3x fa-primary fa secondary"></i>
              </a>

            <li>
            <li class="nav-item">
              <%= link_to users_path, :class => "nav-link" do %>
                <i class="fas fa-user-cog fa-angle-double-right fa-w-14 fa-2x fa-primary"></i>
                <span class="link-text">Usuários</span>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to current_user, :class => "nav-link" do %>
                <i class="fas fa-user-circle fa-angle-double-right fa-w-14 fa-2x fa-primary"></i>
                <span class="link-text">Meu Perfil</span>
              <% end %>
            </li>
            <li class="nav-item">
              <a href="/desafios" class="nav-link">
                <i class="fas fa-gamepad fa-angle-double-right fa-w-14 fa-2x fa-primary"></i>
                <span class="link-text">Desafio</span>
              </a>
            </li>
            <li class="nav-item">
              <%= link_to logout_path, method: "delete", :class => "nav-link" do %>
                <i class="fas fa-sign-out-alt fa-angle-double-right fa-w-14 fa-2x fa-primary"></i>
                <span class="link-text">Logout</span>
                <% end %>
            </li>
            <li class="nav-item" id="themeButton">
              <a href="" class="nav-link">
              <i class="fas fa-glasses fa-angle-double-right fa-w-14 fa-2x fa-primary theme-icon" id="lightIcon"></i>
              <i class="fas fa-sun fa-angle-double-right fa-w-14 fa-2x fa-primary theme-icon" id="solarIcon"></i>
              <i class="fas fa-moon fa-angle-double-right fa-w-14 fa-2x fa-primary theme-icon" id="darkIcon"></i>
              <span class="link-text">Tema</span>
              </a>
            </li>
        </ul>
    </nav>
        <% else %>

        <% end %>
</header>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desafio Amar</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@400;700&display=swap" rel="stylesheet">  
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<section>
<div class="containerA">
    <div class="signup-form">
        <h1>Formulario de edição</h1>
            <%= form_for @user do |f| %>
                <% if @user.errors.any? %>
                    <div id="error_explanation">
                        <div class="alert-error">
                                   O formulário contém <%= pluralize(@user.errors.count, "erro") %>.
                        </div>
                        <ul>
                                   <% @user.errors.full_messages.each do |msg| %>
                                   <li><%= msg %></li>
                                   <% end %>
                        </ul>
                    </div>
                <% end %>
            <%= f.text_field :name , placeholder: 'Novo Nome'%>
            <%= f.text_field :username, placeholder: 'Novo Nome de usuário', :required => true %>
            <%= f.email_field :email, placeholder: 'Novo Email'%>
            <%= f.password_field :password, placeholder: 'Nova Senha', :required => true %>
            <%= f.password_field :password_confirmation, placeholder: 'Confirmar Nova Senha', :required => true %>
            <%= f.submit "Salvar" %>
            <% end %>
    </div>
</div>
</section>
<ul>
            <li><%= link_to "Edit", edit_user_path(current_user) %></li>
            <li><%= link_to "Delete", @user, method: :delete%></li>
</ul>

app/views/users/index.html.erb
  <div class="container">
        <div class="jumbotron">
          <div class="card">
        <div class="card-header">
          Tabela para Administração
        </div>
        <div class="card-body">
          <h5 class="card-title">USUÁRIOS</h5>
          <table class="table table-white table-hover table-bordered">
              <thead>
                <tr>
                  <th scope="col">Id</th>
                  <th scope="col">Nome</th>
                  <th scope="col">Nome de Usuário</th>
                  <th scope="col">Email</th>
                  <th scope="col">AÇÕES</th>
                </tr>
              </thead>
              <tbody>
              <% @users.each do |user| %>
                <tr>
                  <th><%= user.id %></th>
                  <td><%= user.name %></td>
                  <td><%= user.username %></td>
                  <td><%= user.email %></td>
                  <td class="text-right">
                  <%= link_to edit_user_path(user) do %>
                      <button class="btn btn-primary rounded-pill" style="width: 100px;" >EDITAR</button>
                  <% end %>
                  <%= link_to user, method: :delete do %>
                      <button class="btn btn-danger rounded-pill" style="width: 100px;">EXCLUIR</button>
                  <% end %>
                  </td>
                </tr>
              <%end%>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

app/views/users/new.html.erb
<section>
<div class="containerA">
    <div class="signup-form">
        <h1>Cadastro</h1>
            <%= form_for @user do |f| %>
                <% if @user.errors.any? %>
                    <div id="error_explanation">
                        <div class="alert-error">
                                   O formulário contém <%= pluralize(@user.errors.count, "erro") %>.
                        </div>
                        <ul>
                                   <% @user.errors.full_messages.each do |msg| %>
                                   <li><%= msg %></li>
                                   <% end %>
                        </ul>
                    </div>
                <% end %>
            <%= f.text_field :name , placeholder: 'Nome'%>
            <%= f.text_field :username, placeholder: 'Nome de usuário', :required => true %>
            <%= f.email_field :email, placeholder: 'Email'%>
            <%= f.password_field :password, placeholder: 'Senha', :required => true %>
            <%= f.password_field :password_confirmation, placeholder: 'Confirmar Senha', :required => true %>
            <%= f.submit "Cadastrar" %>
            <% end %>
    </div>
</div>
</section>

app/views/users/show.html.erb
<body class="bg-light">
	<div class="container">
     	<div class="row d-flex justify-content-center">
            <div class="col-md-10 mt-5 pt-5">
             	<div class="row z-depth-3">
                 	<div class="col-sm-4 bg-info rounded-left">
        		        <div class="card-block text-center text-white">
                		    <i class="fas fa-user-tie fa-7x mt-5"></i>
                    		<h2 class="font-weight-bold mt-4">Usuário</h2>
                    		<p><%= @user.username %></p><i class="far fa-edit fa-2x mb-4"></i>
                		</div>
            		</div>
            		<div class="col-sm-8 bg-white rounded-right">
                    	<h3 class="mt-3 text-center">Informações</h3>
                    	<hr class="bg-primary mt-0 w-25">
                   		<div class="row">
                        	<div class="col-sm-6">
                            	<p class="font-weight-bold">Nome:</p>
                           		<h6 class=" text-muted"><%= @user.name %></h6>
                        	</div>
                        	<div class="col-sm-6">
                            	<p class="font-weight-bold">Email:</p>
                           		<h6 class="text-muted"><%= @user.email %></h6>
                        	</div>
                    	</div>
                	   	<hr class="bg-primary">
                	    <ul class="list-unstyled d-flex justify-content-center mt-4">
            	        	<li><a href="#!"><i class="fab fa-facebook-f px-3 h4 text-info"></i></a></li>
        	            	<li><a href="#!"><i class="fab fa-youtube px-3 h4 text-info"></i></a></li>
    	                	<li><a href="#!"><i class="fab fa-twitter px-3 h4 text-info"></i></a></li>
	               		</ul>  
              		</div>
             	</div>
            </div>
        </div>
	</div>
</body>